//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string IPAddress { get; set; }
        public string ActivityPage { get; set; }
        public string Remark { get; set; }
    
        public virtual User User { get; set; }
    }
}
