//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmountRouting
    {
        public int Id { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<int> OpId { get; set; }
        public string Amount { get; set; }
        public Nullable<byte> IsROffer { get; set; }
        public Nullable<int> API1_Id { get; set; }
        public Nullable<int> API2_Id { get; set; }
        public Nullable<int> API3_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual ApiSource ApiSource1 { get; set; }
        public virtual ApiSource ApiSource2 { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
    }
}
