//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApiSource()
        {
            this.AmountRoutings = new HashSet<AmountRouting>();
            this.AmountRoutings1 = new HashSet<AmountRouting>();
            this.AmountRoutings2 = new HashSet<AmountRouting>();
            this.ApiRandomKeys = new HashSet<ApiRandomKey>();
            this.ApiUrls = new HashSet<ApiUrl>();
            this.ApiWalletTxns = new HashSet<ApiWalletTxn>();
            this.CircleCodes = new HashSet<CircleCode>();
            this.CircleRoutings = new HashSet<CircleRouting>();
            this.CircleRoutings1 = new HashSet<CircleRouting>();
            this.CircleRoutings2 = new HashSet<CircleRouting>();
            this.CommanRoutings = new HashSet<CommanRouting>();
            this.DMTs = new HashSet<DMT>();
            this.DueAmounts = new HashSet<DueAmount>();
            this.Operators = new HashSet<Operator>();
            this.Operators1 = new HashSet<Operator>();
            this.Operators2 = new HashSet<Operator>();
            this.OperatorCodes = new HashSet<OperatorCode>();
            this.OperatorKeyGenrates = new HashSet<OperatorKeyGenrate>();
            this.Recharges = new HashSet<Recharge>();
            this.TagValues = new HashSet<TagValue>();
            this.Users = new HashSet<User>();
            this.ApiSourceExts = new HashSet<ApiSourceExt>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.BankStatements = new HashSet<BankStatement>();
            this.CommonSwitches = new HashSet<CommonSwitch>();
            this.UserFilterRuleReports = new HashSet<UserFilterRuleReport>();
        }
    
        public int Id { get; set; }
        public string ApiName { get; set; }
        public Nullable<byte> ApiTypeId { get; set; }
        public string ApiUserId { get; set; }
        public string ApiPassword { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> ApiPackid { get; set; }
        public string CallbackId { get; set; }
        public Nullable<decimal> ApiBal { get; set; }
        public Nullable<decimal> ActualBal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusCheckTime { get; set; }
        public Nullable<bool> IsAutoStatusCheck { get; set; }
        public Nullable<int> RequestGap { get; set; }
        public Nullable<decimal> BlockAmount { get; set; }
        public Nullable<int> WaitTime { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> ResendWaitTime { get; set; }
        public Nullable<decimal> CreditBal { get; set; }
        public string ARequestTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountRouting> AmountRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountRouting> AmountRoutings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountRouting> AmountRoutings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiRandomKey> ApiRandomKeys { get; set; }
        public virtual ApiType ApiType { get; set; }
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiUrl> ApiUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiWalletTxn> ApiWalletTxns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircleCode> CircleCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircleRouting> CircleRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircleRouting> CircleRoutings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircleRouting> CircleRoutings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommanRouting> CommanRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMT> DMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DueAmount> DueAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorCode> OperatorCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorKeyGenrate> OperatorKeyGenrates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recharge> Recharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagValue> TagValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiSourceExt> ApiSourceExts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonSwitch> CommonSwitches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFilterRuleReport> UserFilterRuleReports { get; set; }
    }
}
