//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiUrl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApiUrl()
        {
            this.RequestResponses = new HashSet<RequestResponse>();
            this.TagValues = new HashSet<TagValue>();
            this.RechargeGaps = new HashSet<RechargeGap>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ApiId { get; set; }
        public string URL { get; set; }
        public Nullable<byte> UrlTypeId { get; set; }
        public string Method { get; set; }
        public string ContentType { get; set; }
        public string ResType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string PostData { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual ApiUrlType ApiUrlType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResponse> RequestResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagValue> TagValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RechargeGap> RechargeGaps { get; set; }
    }
}
