//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiWalletTxn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApiWalletTxn()
        {
            this.BankStatements = new HashSet<BankStatement>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ApiId { get; set; }
        public System.DateTime TxnDate { get; set; }
        public decimal OP_Bal { get; set; }
        public decimal CR_Amt { get; set; }
        public decimal DB_Amt { get; set; }
        public Nullable<decimal> CL_Bal { get; set; }
        public decimal ApiOpBal { get; set; }
        public decimal ApiClBal { get; set; }
        public Nullable<byte> TxnTypeId { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public string Remark { get; set; }
        public Nullable<long> RefTxnId { get; set; }
        public Nullable<decimal> ClBalDiff { get; set; }
        public Nullable<int> IsOpMatch { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<decimal> Ins_Amt { get; set; }
        public Nullable<long> RecId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        public virtual TxnLedger TxnLedger { get; set; }
        public virtual TxnType TxnType { get; set; }
        public virtual User User { get; set; }
        public virtual DMT DMT { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements { get; set; }
        public virtual Recharge Recharge { get; set; }
    }
}
