//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.BankStatements = new HashSet<BankStatement>();
            this.BankStatements1 = new HashSet<BankStatement>();
            this.WalletRequests = new HashSet<WalletRequest>();
        }
    
        public int Id { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string HolderName { get; set; }
        public string IFSCCode { get; set; }
        public string UpiAdress { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public Nullable<decimal> BlockAmount { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletRequest> WalletRequests { get; set; }
    }
}
