//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatement
    {
        public long Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public decimal OP_Bal { get; set; }
        public decimal CR_Amt { get; set; }
        public decimal DB_Amt { get; set; }
        public Nullable<decimal> CL_Bal { get; set; }
        public Nullable<byte> TxnTypeId { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<int> TrTypeId { get; set; }
        public Nullable<long> TxnId { get; set; }
        public Nullable<long> ApiTxnId { get; set; }
        public Nullable<int> RefAccountId { get; set; }
        public string PaymentRef { get; set; }
        public string Remark { get; set; }
        public string Comment { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<long> DealerTxnId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        public virtual ApiWalletTxn ApiWalletTxn { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual TransferType TransferType { get; set; }
        public virtual TxnLedger TxnLedger { get; set; }
        public virtual TxnType TxnType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
