//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryList
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BenId { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string BeneName { get; set; }
        public string BeneMobileNo { get; set; }
        public string IFSC { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
