//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockRoute
    {
        public int Id { get; set; }
        public string OpFilter { get; set; }
        public string CircleFilter { get; set; }
        public string UserFilter { get; set; }
        public string Amounts { get; set; }
        public string AmountRanges { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> SettingTypeId { get; set; }
        public Nullable<int> SendStatusId { get; set; }
        public string OpTypeFilter { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
