//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircleCode
    {
        public long Id { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public string CircleCode1 { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public string ExtraUrl { get; set; }
        public string ExtraUrlData { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
