//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonSwitch
    {
        public int Id { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<int> Pri { get; set; }
        public Nullable<int> WaitTime { get; set; }
        public string AmountFilter { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string UserFilter { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
