//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommanRouting
    {
        public int Id { get; set; }
        public Nullable<int> OpId { get; set; }
        public string CircleFilter { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<byte> WaitMinute { get; set; }
        public string AmountFilter { get; set; }
        public string UserFilter { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> FTypeId { get; set; }
        public string LapuFilter { get; set; }
        public Nullable<decimal> MinRO { get; set; }
        public string BlockUser { get; set; }
        public string RouteOP1 { get; set; }
        public string RouteOP2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ActiveUpdatedById { get; set; }
        public Nullable<System.DateTime> ActiveUpdatedDate { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual FilterType FilterType { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
