//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public long Id { get; set; }
        public Nullable<long> RecId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public Nullable<int> ComplaintById { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ResolvedById { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsRefund { get; set; }
        public Nullable<long> RefundTxnId { get; set; }
        public Nullable<int> Priorty { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string ApiComplaintId { get; set; }
        public string ApiResponse { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Recharge Recharge { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual TxnLedger TxnLedger { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
