//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMT()
        {
            this.ApiWalletTxns = new HashSet<ApiWalletTxn>();
        }
    
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> TxnId { get; set; }
        public Nullable<int> BId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> RCTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<byte> MediumId { get; set; }
        public string StatusMsg { get; set; }
        public string IPAddress { get; set; }
        public string UserTxnId { get; set; }
        public string OurRefTxnId { get; set; }
        public string ApiTxnId { get; set; }
        public string OptTxnId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string ExternalRefno { get; set; }
        public int WTYPEID { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneMobile { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<decimal> UserComm { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<long> DTxnId { get; set; }
        public Nullable<int> ResendCount { get; set; }
        public string transfermode { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiWalletTxn> ApiWalletTxns { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual MediumType MediumType { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual RCType RCType { get; set; }
        public virtual TxnLedger TxnLedger { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
