//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DueAmount
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> TxnTypeId { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string RefId { get; set; }
        public string PaymentRemark { get; set; }
        public string Comment { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public decimal SentAmt { get; set; }
        public decimal ReceivedAmt { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        public virtual TxnType TxnType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
