//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAPI
    {
        public int Id { get; set; }
        public string ApiName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FromAddress { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> AddedbyId { get; set; }
        public Nullable<int> UpdatebyId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> portNumber { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
