//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelPayoutListverify
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Mobileno { get; set; }
        public string AccountNo { get; set; }
        public string IFSC { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    }
}
