//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSetting
    {
        public int id { get; set; }
        public string Actionname { get; set; }
        public bool AllowSMS { get; set; }
        public bool AllowEmail { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string Displayname { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
