//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operator()
        {
            this.AmountRoutings = new HashSet<AmountRouting>();
            this.CircleRoutings = new HashSet<CircleRouting>();
            this.CommanRoutings = new HashSet<CommanRouting>();
            this.CommonSwitches = new HashSet<CommonSwitch>();
            this.DMTs = new HashSet<DMT>();
            this.OperatorCodes = new HashSet<OperatorCode>();
            this.OperatorKeyGenrates = new HashSet<OperatorKeyGenrate>();
            this.OperatorSerials = new HashSet<OperatorSerial>();
            this.PackageComms = new HashSet<PackageComm>();
            this.PackageCommCircles = new HashSet<PackageCommCircle>();
            this.Recharges = new HashSet<Recharge>();
            this.OperatorValidations = new HashSet<OperatorValidation>();
            this.UserFilterRuleReports = new HashSet<UserFilterRuleReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OpCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsSwitch { get; set; }
        public Nullable<byte> SwitchTypeId { get; set; }
        public Nullable<int> API1_Id { get; set; }
        public Nullable<int> API2_Id { get; set; }
        public Nullable<int> API3_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> OpTypeId { get; set; }
        public Nullable<int> Validate_ApiId { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public Nullable<bool> IsFetch { get; set; }
        public Nullable<int> ValidationLevel { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountRouting> AmountRoutings { get; set; }
        public virtual ApiSource ApiSource { get; set; }
        public virtual ApiSource ApiSource1 { get; set; }
        public virtual ApiSource ApiSource2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CircleRouting> CircleRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommanRouting> CommanRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonSwitch> CommonSwitches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMT> DMTs { get; set; }
        public virtual SwitchType SwitchType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorCode> OperatorCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorKeyGenrate> OperatorKeyGenrates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorSerial> OperatorSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageComm> PackageComms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageCommCircle> PackageCommCircles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recharge> Recharges { get; set; }
        public virtual OperatorType OperatorType { get; set; }
        public virtual OperatorValidType OperatorValidType { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatorValidation> OperatorValidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFilterRuleReport> UserFilterRuleReports { get; set; }
    }
}
