//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorKeyGenrate
    {
        public int Id { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> NoLength { get; set; }
        public Nullable<int> KeyTypeId { get; set; }
        public string TextLength { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedByDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
    }
}
