//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorValidation
    {
        public int Id { get; set; }
        public Nullable<int> OpId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> MinLenth { get; set; }
        public Nullable<int> MaxLenth { get; set; }
        public Nullable<int> MinVal { get; set; }
        public Nullable<int> MaxVal { get; set; }
        public string StartWith { get; set; }
        public string EndWith { get; set; }
        public Nullable<bool> IsNum { get; set; }
        public Nullable<bool> IsString { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
