//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYRC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorSery
    {
        public int Id { get; set; }
        public string Series { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<int> CircleId { get; set; }
    
        public virtual Circle Circle { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
