//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCommRange
    {
        public int Id { get; set; }
        public Nullable<int> PackId { get; set; }
        public string OpTypeFilter { get; set; }
        public string OpFilter { get; set; }
        public string CircleFilter { get; set; }
        public Nullable<int> MinVal { get; set; }
        public Nullable<int> MaxVal { get; set; }
        public Nullable<decimal> CommAmt { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<byte> CommTypeId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<bool> IsUserLoss { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual CommType CommType { get; set; }
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
