//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCommCircle
    {
        public long Id { get; set; }
        public Nullable<int> PackId { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<decimal> CommAmt { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<byte> CommTypeId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<decimal> DailyLimit { get; set; }
        public Nullable<decimal> UsedLimit { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual CommType CommType { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
