//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeGap
    {
        public long Id { get; set; }
        public Nullable<long> RecId { get; set; }
        public string OpCode { get; set; }
        public Nullable<int> UrlId { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> PickTime { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remark { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    
        public virtual ApiUrl ApiUrl { get; set; }
        public virtual Recharge Recharge { get; set; }
    }
}
