//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeGiftCard
    {
        public int Id { get; set; }
        public Nullable<long> RecId { get; set; }
        public string VRechargeId { get; set; }
        public string OrderId { get; set; }
        public string CardId { get; set; }
        public string CardNumber { get; set; }
        public string CardPin { get; set; }
        public string ActivationCode { get; set; }
        public string Barcode { get; set; }
        public string ActivationUrl { get; set; }
        public string APIOrderId { get; set; }
        public string Validity { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual Recharge Recharge { get; set; }
    }
}
