//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recharge()
        {
            this.Complaints = new HashSet<Complaint>();
            this.RechargeGiftCards = new HashSet<RechargeGiftCard>();
            this.RequestResponses = new HashSet<RequestResponse>();
            this.TxnLedgers = new HashSet<TxnLedger>();
            this.RechargeGaps = new HashSet<RechargeGap>();
            this.ApiWalletTxns = new HashSet<ApiWalletTxn>();
        }
    
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<long> TxnId { get; set; }
        public string CustomerNo { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> RCTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<byte> MediumId { get; set; }
        public string StatusMsg { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<decimal> ROfferAmount { get; set; }
        public string UserTxnId { get; set; }
        public string OurRefTxnId { get; set; }
        public string ApiTxnId { get; set; }
        public string OptTxnId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AccountNo { get; set; }
        public string AccountOther { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Optional4 { get; set; }
        public Nullable<System.DateTime> ResendTime { get; set; }
        public Nullable<int> ResendById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<long> LapuId { get; set; }
        public string LapuNo { get; set; }
        public Nullable<long> LapuId2 { get; set; }
        public string LapuNo2 { get; set; }
        public Nullable<decimal> UserComm { get; set; }
        public Nullable<decimal> ApiComm { get; set; }
        public Nullable<decimal> ApiBal { get; set; }
        public Nullable<decimal> UserBal { get; set; }
        public Nullable<int> ResendCount { get; set; }
        public Nullable<bool> IsROChecked { get; set; }
        public Nullable<int> IsValidRO { get; set; }
        public string Comment { get; set; }
        public string beneficiaryIFSC { get; set; }
        public string beneficiaryName { get; set; }
        public string transferMode { get; set; }
        public string AccountBalance { get; set; }
        public Nullable<byte> SettlementType { get; set; }
        public string QrIntent { get; set; }
        public string PaymentUrl { get; set; }
        public string Integration_id { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual Circle Circle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual MediumType MediumType { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual RCType RCType { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual TxnLedger TxnLedger { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RechargeGiftCard> RechargeGiftCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResponse> RequestResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnLedger> TxnLedgers { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RechargeGap> RechargeGaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiWalletTxn> ApiWalletTxns { get; set; }
    }
}
