//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestResponse
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UrlId { get; set; }
        public Nullable<long> RecId { get; set; }
        public string RefId { get; set; }
        public string Remark { get; set; }
        public string RequestTxt { get; set; }
        public string ResponseText { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CustomerNo { get; set; }
        public string UserTxnId { get; set; }
    
        public virtual ApiUrl ApiUrl { get; set; }
        public virtual Recharge Recharge { get; set; }
        public virtual User User { get; set; }
    }
}
