//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsAPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmsAPI()
        {
            this.SMSDatas = new HashSet<SMSData>();
        }
    
        public int Id { get; set; }
        public string ApiName { get; set; }
        public string SENDER_ID { get; set; }
        public string Url { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Method { get; set; }
        public string Parameter { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> AddedbyId { get; set; }
        public Nullable<int> UpdatebyId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSData> SMSDatas { get; set; }
    }
}
