//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSData
    {
        public long Id { get; set; }
        public Nullable<int> Smsid { get; set; }
        public string Mobileno { get; set; }
        public string Message { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> Crdate { get; set; }
    
        public virtual SmsAPI SmsAPI { get; set; }
    }
}
