//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlErrorLog
    {
        public long Id { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorSeverity { get; set; }
        public string ErrorState { get; set; }
        public string ErrorProc { get; set; }
        public string ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
    }
}
