//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagValue
    {
        public int Id { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<int> UrlId { get; set; }
        public Nullable<int> TagId { get; set; }
        public string PreTxt { get; set; }
        public string PostText { get; set; }
        public Nullable<int> PreMargin { get; set; }
        public Nullable<int> PostMargin { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string TagMsg { get; set; }
        public string CompareTxt { get; set; }
        public string ResSeparator { get; set; }
        public Nullable<int> TagIndex { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual ApiUrl ApiUrl { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
