//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TxnLedger()
        {
            this.ApiWalletTxns = new HashSet<ApiWalletTxn>();
            this.BankStatements = new HashSet<BankStatement>();
            this.Complaints = new HashSet<Complaint>();
            this.DMTs = new HashSet<DMT>();
            this.Orders = new HashSet<Order>();
            this.Recharges = new HashSet<Recharge>();
        }
    
        public long Id { get; set; }
        public Nullable<long> RecId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RefTxnId { get; set; }
        public System.DateTime TxnDate { get; set; }
        public decimal OP_Bal { get; set; }
        public decimal CR_Amt { get; set; }
        public decimal DB_Amt { get; set; }
        public Nullable<decimal> CL_Bal { get; set; }
        public Nullable<byte> TxnTypeId { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public string Remark { get; set; }
        public Nullable<long> ApiTxnId { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<long> DMTid { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiWalletTxn> ApiWalletTxns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMT> DMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recharge> Recharges { get; set; }
        public virtual Recharge Recharge { get; set; }
        public virtual TxnType TxnType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
