//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFilterRuleReport
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OpId { get; set; }
        public Nullable<int> CircleId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public Nullable<decimal> AmtPercent { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Roffer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAutoBlock { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> RofferCount { get; set; }
        public Nullable<decimal> RofferRcAmount { get; set; }
    
        public virtual ApiSource ApiSource { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
