//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvEnterprises.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletRequest
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> TxnTypeId { get; set; }
        public Nullable<byte> AmtTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string TxnId { get; set; }
        public string ImagePath { get; set; }
        public string Bankname { get; set; }
        public string Chequeno { get; set; }
        public string PaymentRemark { get; set; }
        public string Comment { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> TrTypeId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsCreditClear { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual AmtType AmtType { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual TransferType TransferType { get; set; }
        public virtual TxnType TxnType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
